### ISSUE TITLE
Changes for MDS 0.4.x

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/mds-provider#79]
Tracking issue for `0.4.x` related updates

* [x] [deprecate support of `0.2.x` line](https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/ReleaseGuidelines.md#ongoing-version-support) **DONE: #90**
* [x] provider schema sub-types have moved (e.g `/dockless/trips.json`) https://github.com/CityOfLosAngeles/mobility-data-specification/pull/336 **DONE: #86**
* [x] ~add `vehicle_type: car` https://github.com/openmobilityfoundation/mobility-data-specification/pull/219~ **N/A**
* [x] add `status_changes.associated_ticket` field https://github.com/openmobilityfoundation/mobility-data-specification/pull/380 **DONE: #92**
* [x] add `trips.currency` field https://github.com/openmobilityfoundation/mobility-data-specification/pull/388 **DONE: #92**
* [x] fix time query param formatting and deprecate non-time params for `/status_changes` and `/trips` https://github.com/openmobilityfoundation/mobility-data-specification/pull/357 **DONE: #91**
* [x] remove paging support for `/status_changes` and `/trips` https://github.com/openmobilityfoundation/mobility-data-specification/pull/424  **DONE: #91**
* [x] add support for `/events` endpoint https://github.com/openmobilityfoundation/mobility-data-specification/pull/357 **DONE: #93**
  * JSON schema validation
  * API queries
  * DB loading
* [x] add support for `/vehicles` endpoint https://github.com/openmobilityfoundation/mobility-data-specification/pull/376 **DONE: #95**
  * JSON schema validation
  * API queries
  * DB loading

**Comment by schnuerle** [comment]
Can this be updated and closed based on 0.4.0 release? 

https://groups.google.com/forum/#!msg/mds-announce/JM3ZOJ7m8e8/n1svUmkeAQAJ

**0.4.0**
Released 2019-10-31

The 0.4.0 release represents a major step forward in the Mobility Data Specification. The provider endpoints have been refactored to allow static file backed API servers which should improve uptime, reliability and the ability to backfill what is now growing to years of data. There is a new policy API endpoint, designed to be implemented by Agencies, that allows for clearer communication of geofencing, vehicle caps and more. A full list of changes is below. Many thanks to all the contributors who helped on this release.

CHANGES

**Provider**

- Improved Handling of Cost Data
- Allow static file storage backed API Endpoints
- Cleanup Provider README
- Legacy Version Header Cleanup
- Internationalization of Currency data
- Specify Types for Query Params
- Clarify the definition of Municipal Boundary
- Update Status Change JSON Schema to include Associated Trip properly

**Agency**

- Add Accuracy Field for GPS Telemetry Data
- String Limit to 255 Characters
- Remove SLA from /telemetry
- Update State Machine Diagram

**Misc**

- New Policy API Endpoint
- Improved README for Schema Directory
- Add Car Vehicle Type
- Unify Error Responses between Provider / Agency
- Improvements to Release Process

**Comment by thekaveman** [comment]
@schnuerle none of this has been implemented in `mds-provider` yet! I am happy to take PRs for any of the various changes needed to support MDS 0.4.x. I think the most pressing is probably the schema directory shuffle, but any help is appreciated.

**Comment by schnuerle** [comment]
Oh I got it now.  This was your area to track provider changes to implement those updates in this repo.  I'll take a look and see if I can help.

**Comment by thekaveman** [comment]
Opened WIP PR #87, please target the `04x` branch for any changes related to MDS 0.4.x support so we can merge all at once.

**Comment by thekaveman** [comment]
Fixed by #87
